# Generated by Django 5.1.7 on 2025-03-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
