# Generated by Django 5.1.7 on 2025-03-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='books',
            field=models.ManyToManyField(to='books.book'),
        ),
    ]
